In [1]:
%matplotlib inline

In [2]:
import scipy.io as spi
import numpy as np
import h5py as h5

import matplotlib.pyplot as plt

def hist(ys, xs=None, y0=0, axs=None):
    if xs is None:
        xs = range(len(ys))
    if axs is None:
        axs = plt.gca()
    return axs.vlines(xs, y0, ys)

In [3]:
hdf = h5.File("dream-trunc3.h5","r")

In [4]:
mat = spi.loadmat("../CSI_GUI/Output/sams/Demo_DREAM/Network_Dataset=Demo_DREAM.mat",
                  squeeze_me=True, struct_as_record=False)
Output = mat['Output']
CSI    = Output.CSI

for j,item in enumerate(CSI):
    psets = item.Parameters.ParentalSet
    for i,ps in enumerate(psets):
        if isinstance(ps,int):
            psets[i] = np.array([ps])

In [7]:
print("""\
genenames      : {genenames}
myfile         : {myfile}
names          : {names}
selected_genes : {selgen}""".format(
        genenames=", ".join(Output.genenames),
        myfile=Output.myfile,
        names=", ".join(Output.names.tolist()),
        selgen=", ".join(str(i) for i in Output.selected_genes)))

genenames      : Gene1, Gene2, Gene3, Gene4, Gene5, Gene6, Gene7, Gene8, Gene9, Gene10
myfile         : Network_Dataset=Demo_DREAM.mat
names          : T1, T2, T3, T4, T5
selected_genes : 1, 2, 3, 4, 5, 6, 7, 8, 9, 10


In [9]:
for item in range(10):
    ps1 = [" ".join(str(i-1) for i in l) for l in CSI[item].Parameters.ParentalSet]
    ps2 = [" ".join(str(i) for i in np.sort(np.hstack([[item],ps]))) for ps in hdf["/{0}/parents".format(item+1)]]

    print("{item} diff: {diff}".format(
            item=item,
            diff=repr(np.setdiff1d(ps1,ps2).tolist())))

0 diff: []
1 diff: []
2 diff: []
3 diff: []
4 diff: []
5 diff: []
6 diff: []
7 diff: []
8 diff: []
9 diff: []


In [10]:
for i in range(10):
    print("{mat} - {py}".format(
            mat=str(np.exp(np.hstack([CSI[i].Parameters.lhyp.cov,CSI[i].Parameters.lhyp.lik]))),
            py=str(hdf["/%i" % (i+1)].attrs["hyperparams"])))

[ 1.84519189  0.7756069   0.30129205] - [ 0.08919124  0.70661332  0.00549028]
[ 1.45056588  0.85018067  0.53791781] - [ 0.28588448  2.4165198   0.00575146]
[ 1.19639188  0.79922205  0.41318194] - [ 0.09643908  0.47710933  0.00431521]
[ 1.6294621   0.81305144  0.27237727] - [ 0.11860427  0.58959473  0.0026932 ]
[ 1.48449319  1.14244433  0.27441474] - [ 0.09211617  0.36412334  0.00210723]
[ 1.17647061  0.82219533  0.22681025] - [ 0.12056756  0.42940065  0.00393761]
[ 1.61610488  1.18270018  0.21961219] - [ 0.13062678  0.42118628  0.00146173]
[ 1.5163359   0.7475496   0.38626565] - [ 0.06457424  0.65418079  0.0062938 ]
[ 1.41632569  0.8261986   0.35492552] - [ 0.1653016   0.62987154  0.00705772]
[ 1.31070159  0.89322742  0.5561551 ] - [ 0.19610735  0.84265548  0.01687036]


In [11]:
par = CSI[0].Parameters

for i in np.argsort(-par.JointDist):
    print("{ps:10s} = {ll:<8.3g}".format(
            ps=" ".join([str(j) for j in par.ParentalSet[i]]),
            ll=par.JointDist[i]))

1 3 9 10   = 0.976   
1 9 10     = 0.0178  
1 2 9 10   = 0.00212 
1 4 9 10   = 0.00128 
1 3 5 9    = 0.000707
1 2 3 9    = 0.000549
1 7 9 10   = 0.000441
1 3 9      = 0.000288
1 5 9 10   = 0.000254
1 8 9 10   = 0.000152
1 2 5 9    = 6.23e-05
1 3 4 9    = 5.33e-05
1 5 9      = 2.21e-05
1 2 9      = 1.78e-05
1 6 9 10   = 1.56e-05
1 3 7 9    = 9.43e-06
1 9        = 9.18e-06
1 4 5 9    = 5.33e-06
1 4 9      = 5.3e-06 
1 3 8 9    = 2.81e-06
1 5 7 9    = 2.12e-06
1 2 7 9    = 1.57e-06
1 2 4 9    = 1.22e-06
1 3 6 9    = 9.7e-07 
1 7 9      = 8.45e-07
1 2 8 9    = 6.97e-07
1 2 6 9    = 6.7e-07 
1 3 5      = 4.15e-07
1 4 7 9    = 2.72e-07
1 3 7 10   = 2.04e-07
1 3 8 10   = 1.79e-07
1 5 8 9    = 1.44e-07
1 3 5 7    = 1.3e-07 
1 3 4 5    = 9.34e-08
1 2 3 10   = 7.01e-08
1 2 3 5    = 6.42e-08
1 5 6 9    = 5.68e-08
1 8 9      = 5.09e-08
1 3 5 8    = 4.35e-08
1 2 8 10   = 2.35e-08
1 4 8 9    = 2.32e-08
1 6 9      = 2.31e-08
1 3 5 6    = 2.16e-08
1 3        = 1.07e-08
1 3 7      = 9.07e-09
1 4 6 9   