In [141]:
import h5py

import itertools as it
import numpy as np

from IPython.display import display, HTML

In [138]:
dt = np.int
data = [[1,2,3],[1,2,3,4,5]]
data = np.array([np.array([i for i in a],dtype=dt) for a in data])

with h5py.File('myfile.hdf5','w') as f:
    h5dt = h5py.special_dtype(vlen=dt)
    dset = f.create_dataset('vlen_int', (5,), dtype=h5dt)
    dset[:] = np.random.rand(5,5)*10

In [139]:
with h5py.File('myfile.hdf5','r') as f:
    df = f['vlen_int']
    display(df[:])

array([array([5, 6, 8, 3, 9]), array([0, 8, 4, 3, 7]),
       array([0, 6, 5, 7, 0]), array([8, 8, 9, 0, 2]),
       array([9, 0, 4, 2, 9])], dtype=object)

In [263]:
with h5py.File('myfile.hdf5','w') as f:
    dt1 = h5py.special_dtype(enum=('i', dict(foo=1, bar=2)))
    df = f.create_dataset('test', (2,2), dtype=dt1)
    df[:] = np.array([[1,1],[0x100,1]])

with h5py.File('myfile.hdf5','r') as f:
    dt2 = f['test'].dtype

print(h5py.check_dtype(enum=dt1))
print(h5py.check_dtype(enum=dt2))

{'foo': 1, 'bar': 2}
{'foo': 1, 'bar': 2}


In [196]:
names = ["foo","bar","baz"]
nmap = dict((n,i) for i,n in enumerate(names))

dt = h5py.special_dtype(enum=(np.int32, nmap))

pset = list(it.chain(([a] for a in names),
                     (list(a) for a in it.permutations(names,2))))

with h5py.File('myfile.hdf5','w') as f:
    dtl = h5py.special_dtype(vlen=dt)
    df = f.create_dataset('pset', (len(pset),), dtype=dt)
    for i,p in enumerate(pset):
        df[i,:] = [nmap[n] for n in p]

display(h5py.check_dtype(enum=h5py.check_dtype(vlen=dtl)))

{'bar': 1, 'baz': 2, 'foo': 0}

In [200]:
with h5py.File('myfile.hdf5','r') as f:
    df = f['pset']
    display(df[:])
    
display(h5py.check_dtype(enum=h5py.check_dtype(vlen=df.dtype)))

array([[0, 0],
       [1, 1],
       [2, 2],
       [0, 1],
       [0, 2],
       [1, 0],
       [1, 2],
       [2, 0],
       [2, 1]], dtype=int32)

AttributeError: 'NoneType' object has no attribute 'metadata'